import { SETTING_KEYS } from "../../domain/settings/setting-keys.ts"
import {
	BEHAVIOR_ANALYZER_PROMPT,
	CHAT_REPLY_PROMPT,
	COMPANY_PROFILER_PROMPT,
	EMAIL_HTML_CONVERTER_PROMPT,
	INTENT_CLASSIFIER_PROMPT,
	REPLY_PERSONALIZER_PROMPT,
	SEQUENCE_GENERATOR_PROMPT,
	SUBJECT_LINE_PICKER_PROMPT,
	WEBSITE_ANALYZER_PROMPT,
} from "../ai/prompts/index.ts"

export const DEFAULT_SETTINGS = [
	// ── AI: Models ──
	{
		key: SETTING_KEYS.AI_MODEL_BEHAVIOR_ANALYZER,
		value: "openai/gpt-4o",
		category: "ai",
		label: "Behavior Analyzer Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_WEBSITE_ANALYZER,
		value: "openai/o3-mini",
		category: "ai",
		label: "Website Analyzer Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_COMPANY_PROFILER,
		value: "openai/gpt-4.1-mini",
		category: "ai",
		label: "Company Profiler Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_EMAIL_GENERATOR,
		value: "openai/gpt-4o-mini",
		category: "ai",
		label: "Email Generator Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_HTML_CONVERTER,
		value: "openai/gpt-4o-mini",
		category: "ai",
		label: "HTML Converter Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_REPLY_PERSONALIZER,
		value: "openai/o3-mini",
		category: "ai",
		label: "Reply Personalizer Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_SUBJECT_LINE_PICKER,
		value: "openai/gpt-4o-mini",
		category: "ai",
		label: "Subject Line Picker Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_INTENT_CLASSIFIER,
		value: "openai/gpt-4o-mini",
		category: "ai",
		label: "Intent Classifier Model",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.AI_MODEL_CHAT_REPLY,
		value: "openai/gpt-4o",
		category: "ai",
		label: "Chat Reply Model",
		valueType: "string",
	},

	// ── AI: Temperature ──
	{
		key: SETTING_KEYS.AI_TEMPERATURE_DEFAULT,
		value: 0.7,
		category: "ai",
		label: "Default Temperature",
		valueType: "number",
	},
	{
		key: SETTING_KEYS.AI_TEMPERATURE_COMPANY_PROFILER,
		value: 0.5,
		category: "ai",
		label: "Company Profiler Temperature",
		valueType: "number",
	},
	{
		key: SETTING_KEYS.AI_TEMPERATURE_HTML_CONVERTER,
		value: 0.3,
		category: "ai",
		label: "HTML Converter Temperature",
		valueType: "number",
	},

	// ── AI: Prompts ──
	{
		key: SETTING_KEYS.AI_PROMPT_BEHAVIOR_ANALYZER,
		value: BEHAVIOR_ANALYZER_PROMPT,
		category: "ai",
		label: "Behavior Analyzer Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_SEQUENCE_GENERATOR,
		value: SEQUENCE_GENERATOR_PROMPT,
		category: "ai",
		label: "Sequence Generator Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_WEBSITE_ANALYZER,
		value: WEBSITE_ANALYZER_PROMPT,
		category: "ai",
		label: "Website Analyzer Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_COMPANY_PROFILER,
		value: COMPANY_PROFILER_PROMPT,
		category: "ai",
		label: "Company Profiler Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_HTML_CONVERTER,
		value: EMAIL_HTML_CONVERTER_PROMPT,
		category: "ai",
		label: "Email HTML Converter Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_REPLY_PERSONALIZER,
		value: REPLY_PERSONALIZER_PROMPT,
		category: "ai",
		label: "Reply Personalizer Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_SUBJECT_LINE_PICKER,
		value: SUBJECT_LINE_PICKER_PROMPT,
		category: "ai",
		label: "Subject Line Picker Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_INTENT_CLASSIFIER,
		value: INTENT_CLASSIFIER_PROMPT,
		category: "ai",
		label: "Intent Classifier Prompt",
		valueType: "text",
	},
	{
		key: SETTING_KEYS.AI_PROMPT_CHAT_REPLY,
		value: CHAT_REPLY_PROMPT,
		category: "ai",
		label: "Chat Reply Prompt",
		valueType: "text",
	},

	// ── AI: Content Limits ──
	{
		key: SETTING_KEYS.AI_LIMIT_WEBSITE_MARKDOWN_CHARS,
		value: 15000,
		category: "ai",
		label: "Website Markdown Char Limit",
		valueType: "number",
	},
	{
		key: SETTING_KEYS.AI_LIMIT_COMPANY_CONTENT_CHARS,
		value: 10000,
		category: "ai",
		label: "Company Content Char Limit",
		valueType: "number",
	},
	{
		key: SETTING_KEYS.AI_LIMIT_SCRAPER_FALLBACK_CHARS,
		value: 20000,
		category: "ai",
		label: "Scraper Fallback Char Limit",
		valueType: "number",
	},
	{
		key: SETTING_KEYS.AI_RETRY_MAX_RETRIES,
		value: 3,
		category: "ai",
		label: "Max API Retries",
		valueType: "number",
	},

	// ── Email ──
	{
		key: SETTING_KEYS.EMAIL_SENDER_NAME,
		value: "KUNCI AI SDR",
		category: "email",
		label: "Sender Name",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.EMAIL_SENDER_COMPANY,
		value: "KUNCI.AI",
		category: "email",
		label: "Sender Company",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.EMAIL_SENDER_EMAIL,
		value: "",
		category: "email",
		label: "Sender Email",
		valueType: "string",
		description: "Overrides env.SENDER_EMAIL if set",
	},
	{
		key: SETTING_KEYS.EMAIL_COLOR_PRIMARY,
		value: "#2563eb",
		category: "email",
		label: "Primary Color",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.EMAIL_COLOR_ACCENT,
		value: "#f97316",
		category: "email",
		label: "Accent Color",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.EMAIL_COLOR_CTA,
		value: "#16a34a",
		category: "email",
		label: "CTA Button Color",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.EMAIL_COLOR_TEXT,
		value: "#374151",
		category: "email",
		label: "Text Color",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.EMAIL_COLOR_BACKGROUND,
		value: "#ffffff",
		category: "email",
		label: "Background Color",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.EMAIL_FONT_FAMILY,
		value: "Arial, Helvetica, sans-serif",
		category: "email",
		label: "Font Family",
		valueType: "string",
	},

	// ── Business Profile ──
	{
		key: SETTING_KEYS.BUSINESS_NAME,
		value: "",
		category: "business",
		label: "Company Name",
		valueType: "string",
		description: "Your company/brand name as it appears in outreach emails",
	},
	{
		key: SETTING_KEYS.BUSINESS_DESCRIPTION,
		value: "",
		category: "business",
		label: "Business Description",
		valueType: "text",
		description: "Brief description of what your company does (2-3 sentences)",
	},
	{
		key: SETTING_KEYS.BUSINESS_INDUSTRY,
		value: "",
		category: "business",
		label: "Industry",
		valueType: "string",
		description: "Your industry category (e.g., SaaS, Consulting, Marketing)",
	},
	{
		key: SETTING_KEYS.BUSINESS_VALUE_PROPOSITION,
		value: "",
		category: "business",
		label: "Value Proposition",
		valueType: "text",
		description: "Your unique value proposition — what makes you different",
	},
	{
		key: SETTING_KEYS.BUSINESS_TARGET_MARKET,
		value: "",
		category: "business",
		label: "Target Market",
		valueType: "string",
		description: "Who you serve (e.g., SMBs, Enterprise, Startups)",
	},
	{
		key: SETTING_KEYS.BUSINESS_TONE_OF_VOICE,
		value: "professional",
		category: "business",
		label: "Email Tone of Voice",
		valueType: "string",
		description:
			"Communication style: professional, casual, friendly, authoritative",
	},
	{
		key: SETTING_KEYS.BUSINESS_WEBSITE,
		value: "",
		category: "business",
		label: "Company Website",
		valueType: "string",
		description: "Your company website URL",
	},
	{
		key: SETTING_KEYS.BUSINESS_OFFERINGS,
		value: [],
		category: "business",
		label: "Products & Services",
		valueType: "json",
		description: "List of products and services you offer",
	},

	// ── Pipeline ──
	{
		key: SETTING_KEYS.PIPELINE_EMAIL_SEQUENCE_COUNT,
		value: 3,
		category: "pipeline",
		label: "Email Sequence Count",
		valueType: "number",
	},
	{
		key: SETTING_KEYS.PIPELINE_BULK_IMPORT_MAX,
		value: 100,
		category: "pipeline",
		label: "Max Bulk Import Leads",
		valueType: "number",
	},

	// ── Scheduler ──
	{
		key: SETTING_KEYS.SCHEDULER_CRON_EXPRESSION,
		value: "30 9 * * *",
		category: "scheduler",
		label: "Follow-up Cron Expression",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.SCHEDULER_CRON_TIMEZONE,
		value: "UTC",
		category: "scheduler",
		label: "Cron Timezone",
		valueType: "string",
	},
	{
		key: SETTING_KEYS.SCHEDULER_FOLLOWUP_DELAY_DAYS,
		value: 4,
		category: "scheduler",
		label: "Follow-up Delay (days)",
		valueType: "number",
	},
	{
		key: SETTING_KEYS.SCHEDULER_ENABLED,
		value: true,
		category: "scheduler",
		label: "Scheduler Enabled",
		valueType: "boolean",
	},

	// ── Auto-reply chat ──
	{
		key: SETTING_KEYS.AUTO_REPLY_MAX_TURNS,
		value: 6,
		category: "auto_reply",
		label: "Max AI Auto-Reply Turns",
		valueType: "number",
		description:
			"Maximum number of AI-generated outbound replies per lead after initial sequence. Hard cap to prevent runaway loops.",
	},
	{
		key: SETTING_KEYS.AUTO_REPLY_DELAY_MIN_MS,
		value: 180_000,
		category: "auto_reply",
		label: "Auto-Reply Min Delay (ms)",
		valueType: "number",
		description:
			"Lower bound for randomized delay before sending an AI reply. Makes the agent feel human.",
	},
	{
		key: SETTING_KEYS.AUTO_REPLY_DELAY_MAX_MS,
		value: 900_000,
		category: "auto_reply",
		label: "Auto-Reply Max Delay (ms)",
		valueType: "number",
		description:
			"Upper bound for randomized delay before sending an AI reply.",
	},
]
